name: Test And Create Coverage
on:
  push:
    branches: [ mainline ]
  workflow_dispatch:
jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.1
    - name: Test Go
      run: go test -v ./... -cover
    - name: Validate Go Coverage Is 100%
      run: ./test-coverage.sh
    - name: TODO somehow pass correct coverprofile to next step
      run: echo 'TODO'
    - name: Update coverage badge
      uses: ncruces/go-coverage-report@v0
      with:
        context: .
        coverage-file: coverprofile